// Package state defines the Shared State Repository (SSR) data model.
//
// The SSR is the single source of truth for Sentinel's runtime state.
// Each core subsystem owns exactly one state object.
// These models intentionally start empty in v1 and are extended
// incrementally as each subsystem is implemented.
package state

// ObservationState contains the runtime state produced by the
// Observation Manager.
//
// Ownership:
//
//	Observation Manager
type ObservationState struct{}

// AnalysisState contains the workload analysis generated by the
// Analysis Engine.
//
// Ownership:
//
//	Analysis Engine
type AnalysisState struct{}

// DecisionState contains policy decisions generated by the
// Decision Engine.
//
// Ownership:
//
//	Decision Engine
type DecisionState struct{}

// PlannerState contains the Adaptive Execution Strategy (AES)
// produced by the Execution Planner.
//
// Ownership:
//
//	Execution Planner
type PlannerState struct{}

// BackendState contains the execution status reported by the
// Backend Manager.
//
// Ownership:
//
//	Backend Manager
type BackendState struct{}

// TelemetryState contains runtime metrics and health information
// collected by the Telemetry Engine.
//
// Ownership:
//
//	Telemetry Engine
type TelemetryState struct{}

// ReconciliationState contains the desired state, current state,
// and computed differences maintained by the Reconciliation Engine.
//
// Ownership:
//
//	Reconciliation Engine
type ReconciliationState struct{}
