package state

import "time"

// -----------------------------------------------------------------------------
// Observation
// -----------------------------------------------------------------------------

// ObservationState represents one complete observation cycle of the host.
//
// It is the canonical runtime snapshot produced by the Observation Engine.
// Every collector contributes to this single object before it is published
// into the Shared State Repository (SSR).
type ObservationState struct {
	Timestamp  time.Time
	Generation uint64

	CPU        CPUState
	Memory     MemoryState
	Network    NetworkState
	Process    ProcessState
	Filesystem FilesystemState
}

// -----------------------------------------------------------------------------
// CPU
// -----------------------------------------------------------------------------

// CPUState represents the observed CPU state.
type CPUState struct {
	UsagePercent float64
	CoreCount    int
	LoadAverage  float64
}

// -----------------------------------------------------------------------------
// Memory
// -----------------------------------------------------------------------------

// MemoryState represents the observed memory state.
type MemoryState struct {
	Total uint64
	Used  uint64
	Free  uint64

	UsagePercent float64
}

// -----------------------------------------------------------------------------
// Network
// -----------------------------------------------------------------------------

// NetworkState represents network statistics.
type NetworkState struct {
	BytesReceived uint64
	BytesSent     uint64

	PacketsReceived uint64
	PacketsSent     uint64
}

// -----------------------------------------------------------------------------
// Process
// -----------------------------------------------------------------------------

// ProcessState represents process information.
type ProcessState struct {
	Running int
	Blocked int
	Zombie  int
}

// -----------------------------------------------------------------------------
// Filesystem
// -----------------------------------------------------------------------------

// FilesystemState represents filesystem usage.
type FilesystemState struct {
	Total uint64
	Used  uint64
	Free  uint64

	UsagePercent float64
}

// -----------------------------------------------------------------------------
// Analysis
// -----------------------------------------------------------------------------

// AnalysisState contains the output of the Analysis Engine.
type AnalysisState struct {
	Timestamp time.Time
}

// -----------------------------------------------------------------------------
// Decision
// -----------------------------------------------------------------------------

// DecisionState contains decisions generated by the Decision Engine.
type DecisionState struct {
	Timestamp time.Time
}

// -----------------------------------------------------------------------------
// Planner
// -----------------------------------------------------------------------------

// PlannerState contains the execution plan produced by the Planner.
type PlannerState struct {
	Timestamp time.Time
}

// -----------------------------------------------------------------------------
// Backend
// -----------------------------------------------------------------------------

// BackendState contains backend execution status.
type BackendState struct {
	Timestamp time.Time
}

// -----------------------------------------------------------------------------
// Telemetry
// -----------------------------------------------------------------------------

// TelemetryState contains telemetry exported by Sentinel.
type TelemetryState struct {
	Timestamp time.Time
}

// -----------------------------------------------------------------------------
// Reconciliation
// -----------------------------------------------------------------------------

// ReconciliationState contains reconciliation status.
type ReconciliationState struct {
	Timestamp time.Time
}
